AWSTemplateFormatVersion: 2010-09-09
Description: Table nested stack template

Parameters:
  pTagEnv:
    Description: Tag name environment
    Type: String

  pTagProyect:
    Description: Tag name project
    Type: String

  pGlueJobAnalyticsMaestroMaestroEquipos:
    Description: Job name analytics maestro
    Type: String

  pGlueJobAnalyticsMaestroMaestroEquiposUsuarios:
    Description: Job name analytics maestro equipo usuarios
    Type: String

  pGlueJobAnalyticsScriptLocationMaestroMaestroEquipos:
    Description: Job name analytics script
    Type: String

  pGlueJobAnalyticsScriptLocationMaestroMaestroEquiposUsuarios:
    Description: Job name analytics script
    Type: String

  pS3BucketAnalytics:
    Description: Bucket name analytics
    Type: String

  pGlueTableAnalyticsMaestroMaestroEquipos:
    Description: Table name analytics maestro
    Type: String

  pGlueTableAnalyticsMaestroMaestroEquiposUsuarios:
    Description: Table name analytics maestro equipos usuarios
    Type: String

  pGlueJobAnalyticsMaestroTempDir:
    Description: Job name analytics maestro temp
    Type: String

  pProcessingGlueExecutionRoleStack:
    Description: Glue rol name
    Type: String

  pAwsRegion:
    Description: Region name
    Type: String

  pSourceDatabase:
    Description: Data base name stage
    Type: String

  pSourceTableCalendario:
    Description: table name stage
    Type: String

  pSourceTableCargo:
    Description: table name stage
    Type: String

  pSourceTableCargoTipo:
    Description: table name stage
    Type: String

  pSourceTableCuenta:
    Description: table name stage
    Type: String

  pSourceTableEmpleado:
    Description: table name stage
    Type: String

  pSourceTableEmpleadoCuenta:
    Description: table name stage
    Type: String

  pSourceTableEmpleadoModalidadTrabajo:
    Description: table name stage
    Type: String

  pSourceTableEmpleadoServicio:
    Description: table name stage
    Type: String

  pSourceTableEmpleadoSuperiores:
    Description: table name stage
    Type: String

  pSourceTableEmpleadoUbicacion:
    Description: table name stage
    Type: String

  pSourceTableModalidadTrabajo:
    Description: table name stage
    Type: String

  pSourceTableServicios:
    Description: .table name stage
    Type: String

  pSourceTableSite:
    Description: table name stage
    Type: String

  pSourceTableSociedad:
    Description: table name stage
    Type: String

  pSourceTableSubarea:
    Description: table name stage
    Type: String

  pSourceTablempleadoCuentaLucent:
    Description: table name stage
    Type: String

  pSourceTableEmpleadoSistemaExterno:
    Description: table name stage
    Type: String

  pSourceTableSistemaExterno:
    Description: table name stage
    Type: String

  pTargetDatabase:
    Description: Data base name analytics
    Type: String

Resources:
  rGlueJobAnalyticsMaestroMaestroEquipos:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref pGlueJobAnalyticsMaestroMaestroEquipos
      Description: Join data
      GlueVersion: 3.0
      Role: !Ref pProcessingGlueExecutionRoleStack
      Command:
        Name: glueetl
        ScriptLocation: !Ref pGlueJobAnalyticsScriptLocationMaestroMaestroEquipos
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-disable"
        '--job-language': python
        '--TempDir': !Ref pGlueJobAnalyticsMaestroTempDir
        "--AWS_REGION": !Ref pAwsRegion
        "--PARAM_INT_DAYS": 3
        "--SOURCE_DATABASE": !Ref pSourceDatabase
        "--SOURCE_TABLE_CALENDARIO": !Ref pSourceTableCalendario
        "--SOURCE_TABLE_CARGO": !Ref pSourceTableCargo
        "--SOURCE_TABLE_CARGO_TIPO": !Ref pSourceTableCargoTipo
        "--SOURCE_TABLE_CUENTA": !Ref pSourceTableCuenta
        "--SOURCE_TABLE_EMPLEADO": !Ref pSourceTableEmpleado
        "--SOURCE_TABLE_EMPLEADO_CUENTA": !Ref pSourceTableEmpleadoCuenta
        "--SOURCE_TABLE_EMPLEADO_MODALIDAD_TRABAJO": !Ref pSourceTableEmpleadoModalidadTrabajo
        "--SOURCE_TABLE_EMPLEADO_SERVICIO": !Ref pSourceTableEmpleadoServicio
        "--SOURCE_TABLE_EMPLEADO_SUPERIORES": !Ref pSourceTableEmpleadoSuperiores
        "--SOURCE_TABLE_EMPLEADO_UBICACION": !Ref pSourceTableEmpleadoUbicacion
        "--SOURCE_TABLE_MODALIDAD_TRABAJO": !Ref pSourceTableModalidadTrabajo
        "--SOURCE_TABLE_SERVICIOS": !Ref pSourceTableServicios
        "--SOURCE_TABLE_SITE": !Ref pSourceTableSite
        "--SOURCE_TABLE_SOCIEDAD": !Ref pSourceTableSociedad
        "--SOURCE_TABLE_SUBAREA": !Ref pSourceTableSubarea
        "--TARGET_BUCKET": !Sub "s3://${pS3BucketAnalytics}/maestro/${pGlueTableAnalyticsMaestroMaestroEquipos}"
        "--TARGET_DATABASE": !Ref pTargetDatabase
        "--TARGET_TABLE_MAESTRO_EQUIPOS": !Ref pGlueTableAnalyticsMaestroMaestroEquipos
      MaxRetries: 0
      NumberOfWorkers: 5
      Tags:
        "ENV" : !Ref pTagEnv
        "PROYECT": !Ref pTagProyect
        "Name": !Ref pGlueJobAnalyticsMaestroMaestroEquipos
      Timeout: 10
      WorkerType: G.1X

  rGlueJobAnalyticsMaestroMaestroEquiposUsuarios:
    Type: AWS::Glue::Job
    Properties:
      Name: !Ref pGlueJobAnalyticsMaestroMaestroEquiposUsuarios
      Description: Join data
      GlueVersion: 3.0
      Role: !Ref pProcessingGlueExecutionRoleStack
      Command:
        Name: glueetl
        ScriptLocation: !Ref pGlueJobAnalyticsScriptLocationMaestroMaestroEquiposUsuarios
      DefaultArguments:
        "--job-bookmark-option": "job-bookmark-disable"
        '--job-language': python
        '--TempDir': !Ref pGlueJobAnalyticsMaestroTempDir
        "--AWS_REGION": !Ref pAwsRegion
        "--PARAM_INT_DAYS": 3
        "--SOURCE_DATABASE": !Ref pSourceDatabase
        "--SOURCE_TABLE_CALENDARIO": !Ref pSourceTableCalendario
        "--SOURCE_TABLE_EMPLEADO_CUENTA_LUCENT": !Ref pSourceTablempleadoCuentaLucent
        "--SOURCE_TABLE_EMPLEADO_SISTEMA_EXTERNO": !Ref pSourceTableEmpleadoSistemaExterno
        "--SOURCE_TABLE_SISTEMA_EXTERNO": !Ref pSourceTableSistemaExterno
        "--TARGET_BUCKET": !Sub "s3://${pS3BucketAnalytics}/maestro/${pGlueTableAnalyticsMaestroMaestroEquiposUsuarios}"
        "--TARGET_DATABASE": !Ref pTargetDatabase
        "--TARGET_TABLE_MAESTRO_EQUIPOS_USUARIOS": !Ref pGlueTableAnalyticsMaestroMaestroEquiposUsuarios
      MaxRetries: 0
      NumberOfWorkers: 5
      Tags:
        "ENV" : !Ref pTagEnv
        "PROYECT": !Ref pTagProyect
        "Name": !Ref pGlueJobAnalyticsMaestroMaestroEquiposUsuarios
      Timeout: 10
      WorkerType: G.1X

Outputs:
  rGlueJobAnalyticsMaestroMaestroEquiposName:
    Description: Id for the job
    Value: !Ref rGlueJobAnalyticsMaestroMaestroEquipos

  rGlueJobAnalyticsMaestroMaestroEquiposUsuariosName:
    Description: Id for the job
    Value: !Ref rGlueJobAnalyticsMaestroMaestroEquiposUsuarios
