AWSTemplateFormatVersion: 2010-09-09
Description: Table nested stack template

Parameters:
  pTagEnv:
    Description: Tag name environment
    Type: String

  pTagProyect:
    Description: Tag name project
    Type: String

  pGlueCrawlerStageMeucci2a:
    Description: Crawler name stage meucci2a
    Type: String

  pGlueDatabaseStage:
    Description: Data base name stage
    Type: String

  pGlueCrawlerStageMeucci2aPathRoot:
    Description: Crawler stage path root
    Type: String

  pProcessingGlueExecutionRoleStack:
    Description: Glue role name
    Type: String

Resources:
  rGlueCrawlerStageMeucci2a:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref pGlueCrawlerStageMeucci2a
      Role: !Ref pProcessingGlueExecutionRoleStack
      DatabaseName: !Ref pGlueDatabaseStage
      Targets:
        S3Targets:
          - Path: !Ref pGlueCrawlerStageMeucci2aPathRoot
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: "{\"Version\": 1.0,\"Grouping\":{\"TableGroupingPolicy\":\"CombineCompatibleSchemas\",\"TableLevelConfiguration\":3}}"
      Tags:
        "ENV" : !Ref pTagEnv
        "PROYECT": !Ref pTagProyect
        "Name": !Ref pGlueCrawlerStageMeucci2a

Outputs:
  rGlueCrawlerStageMeucci2aName:
    Description: Id for the crawler
    Value: !Ref rGlueCrawlerStageMeucci2a