AWSTemplateFormatVersion: 2010-09-09
Description: Deploy Data Lake Konecta project resources

Parameters: 
# Tags
  pTagEnv:
    Description: Tag name environment
    Type: String
    Default: DEV

  pTagProyect:
    Description: Tag name project
    Type: String
    Default: DataLake

# Buckets
  pS3BucketRaw:
    Description: Bucket name raw dev
    Type: String
    Default: knta-dev-00-datalake-raw

  pS3BucketStage:
    Description: Bucket name stage dev
    Type: String
    Default: knta-dev-00-datalake-stage

  pS3BucketAnalytics:
    Description: Bucket name analytics dev
    Type: String
    Default: knta-dev-00-datalake-analytics
    
# Databases
  pGlueDatabaseStage:
    Description: Data base name stage
    Type: String
    Default: knta-dev-00-gluedb-datalake-stage

  pGlueDatabaseAnalytics:
    Description: Data base name analytics
    Type: String
    Default: knta-dev-00-gluedb-datalake-analytics

# Template Jobs
  TemplateURLJobsAnalytics:
    Description: URL of the nested stack template
    Type: String
    Default: https://knta-dev-00-cloudformation-stack.s3.amazonaws.com/maestro-equipos/glue/jobs-analytics.yaml

# Process Crawlers
  TemplateURLCrawlersAnalytics:
    Description: URL of the nested stack template
    Type: String
    Default: https://knta-dev-00-cloudformation-stack.s3.amazonaws.com/maestro-equipos/glue/crawlers-analytics.yaml

  pGlueCrawlerAnalyticsMaestro:
    Description: Crawler name analytics
    Type: String
    Default: knta-dev-00-gluecrawler-datalake-analytics-maestro

  pGlueCrawlerAnalyticsMaestroPathRoot:
    Description: Crawler analytics path root
    Type: String
    Default: s3://knta-dev-00-datalake-analytics/maestro/

# Process Triggers
  pGlueCrawlerTriggerAnalyticsMaestro:
    Description: Trigger crawler name maestro
    Type: String 
    Default: knta-dev-00-gluecrawlertrigger-datalake-analytics-maestro

  pGlueJobTriggerAnalyticsMaestro:
    Description: Trigger job name maestro
    Type: String  
    Default: knta-dev-00-gluecjobtrigger-datalake-analitycs-maestro

  TemplateURLTriggerAnalytics:
    Description: URL of the nested stack template
    Type: String
    Default: https://knta-dev-00-cloudformation-stack.s3.amazonaws.com/maestro-equipos/glue/triggers-analytics.yaml

# Process Calendario
  pGlueTableStageMeucci2aCalendario:
    Description: Table name stage
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_calendario

# Process Cargo
  pGlueTableStageMeucci2aCargo:
    Description: Table name stage cargo
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_cargo

# Process Cargo-tipo
  pGlueTableStageMeucci2aCargotipo:
    Description: Table name stage cargotipo
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_cargo_tipo

# Process Cuenta
  pGlueTableStageMeucci2aCuenta:
    Description: Table name stage cuenta
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_cuenta

# Process Empleado
  pGlueTableStageMeucci2aEmpleado:
    Description: Table name stage empleado
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_empleado

# Process Empleado-Cuenta
  pGlueTableStageMeucci2aEmpleadoCuenta:
    Description: Table name stage empleadocuenta
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_empleado_cuenta

# Process Empleado-Modalidad-Trabajo
  pGlueTableStageMeucci2aEmpleadoModalidadTrabajo:
    Description: Table name stage modalidadtrabajo
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_empleado_modalidad_trabajo

# Process Empleado-Servicio
  pGlueTableStageMeucci2aEmpleadoServicio:
    Description: Table name stage empleadoservicio
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_empleado_servicio

# Process Empleado-Superiores
  pGlueTableStageMeucci2aEmpleadoSuperiores:
    Description: Table name stage empleadosuperiores
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_empleado_superiores

# Process Empleado-Ubicacion
  pGlueTableStageMeucci2aEmpleadoUbicacion:
    Description: Table name stage empleadoubicacion
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_empleado_ubicacion

# Process Modalidad-Trabajo
  pGlueTableStageMeucci2aModalidadTrabajo:
    Description: Table name stage modalidadtrabajo
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_modalidad_trabajo

# Process Servicios
  pGlueTableStageMeucci2aServicios:
    Description: Table name stage servicios
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_servicios

# Process Site
  pGlueTableStageMeucci2aSite:
    Description: Table name stage site
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_site

# Process Sociedad
  pGlueTableStageMeucci2aSociedad:
    Description: Table name stage sociedad
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_sociedad

# Process Subarea
  pGlueTableStageMeucci2aSubarea:
    Description: Table name stage subarea
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_subarea

# Process Empleado-Cuenta-Lucent
  pGlueTableStageMeucci2aEmpleadoCuentaLucent:
    Description: Table name stage empleadocuentalucent
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_empleado_cuentalucent
    
# Process Empleado-Sistema-Externo
  pGlueTableStageMeucci2aEmpleadoSistemaExterno:
    Description: Table name stage empleadosistemaexterno
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_empleado_sistemaexterno

# Process Sistema-externo
  pGlueTableStageMeucci2aSistemaExterno:
    Description: Table name stage sistemaexterno
    Type: String
    Default: knta_dev_00_gluetable_datalake_stage_meucci2a_dbo_sistemaexterno

# Process Maestro-Equipos
  pGlueTableAnalyticsMaestroMaestroEquipos:
    Description: Table name analytics maestroequipos
    Type: String
    Default: knta_dev_00_gluetable_datalake_analytics_maestro_base_maestro_equipos

  pGlueJobAnalyticsMaestroMaestroEquipos:
    Description: Job name analytics maestroequipos
    Type: String
    Default: knta-dev-00-gluejob-datalake-analytics-maestro-base-maestro-equipos

  pGlueJobAnalyticsScriptLocationMaestroMaestroEquipos:
    Description: Python script location maestro
    Type: String
    Default: s3://knta-dev-00-gluejob-scripts/datalake/maestro-equipos/scripts/knta-dev-00-gluejob-datalake-analytics-maestro-base-maestro-equipos.py

# Process Maestro-Equipos-Ususarios
  pGlueTableAnalyticsMaestroMaestroEquiposUsuarios:
    Description: Table name analytics maestroequiposusuarios
    Type: String
    Default: knta_dev_00_gluetable_datalake_analytics_maestro_base_maestro_equipos_usuarios

  pGlueJobAnalyticsMaestroMaestroEquiposUsuarios:
    Description: Job name analytics maestroequiposusuarios
    Type: String
    Default: knta-dev-00-gluejob-datalake-analytics-maestro-base-maestro-equipos-usuarios

  pGlueJobAnalyticsScriptLocationMaestroMaestroEquiposUsuarios:
    Description: Python script location maestrousuarios
    Type: String
    Default: s3://knta-dev-00-gluejob-scripts/datalake/maestro-equipos/scripts/knta-dev-00-gluejob-datalake-analytics-maestro-base-maestro-equipos-usuarios.py


# Job scripts
  pGlueJobAnalyticsMaestroTempDir:
    Description: Temporary directory location maestro
    Type: String
    Default: s3://knta-dev-00-gluejob-scripts/datalake/maestro-equipos/temp/

# Process Workflow
  pGlueWorkflowMaestro:
    Description: Workflow name
    Type: String
    Default: knta-dev-00-glueworkflow-datalake-maestro

  TemplateURLWorkflows:
    Description: URL of the nested stack template
    Type: String
    Default: https://knta-dev-00-cloudformation-stack.s3.amazonaws.com/maestro-equipos/glue/workflows.yaml

# Parameters Aditionals
  pAwsRegion:
    Description: Region name
    Type: String
    Default: us-east-1

  pArnGlueExecutionRoleStack:
    Description: Glue rol name
    Type: String
    Default: arn:aws:iam::939108293311:role/knta-dev-00-iamrole-datalake-glue-startjobcrawler

Resources:
  rGlueJobsAnalyticsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateURLJobsAnalytics
      Parameters:
        pTagEnv: !Ref pTagEnv
        pTagProyect: !Ref pTagProyect
        pGlueJobAnalyticsMaestroTempDir: !Ref pGlueJobAnalyticsMaestroTempDir
        pProcessingGlueExecutionRoleStack: !Ref pArnGlueExecutionRoleStack
        pS3BucketAnalytics: !Ref pS3BucketAnalytics
        pAwsRegion: !Ref pAwsRegion
        pSourceDatabase: !Ref pGlueDatabaseStage
        pTargetDatabase: !Ref pGlueDatabaseAnalytics
        # Maestro-Equipos
        pGlueJobAnalyticsMaestroMaestroEquipos: !Ref pGlueJobAnalyticsMaestroMaestroEquipos
        pGlueJobAnalyticsScriptLocationMaestroMaestroEquipos: !Ref pGlueJobAnalyticsScriptLocationMaestroMaestroEquipos
        pGlueTableAnalyticsMaestroMaestroEquipos: !Ref pGlueTableAnalyticsMaestroMaestroEquipos
        pSourceTableCalendario: !Ref pGlueTableStageMeucci2aCalendario
        pSourceTableCargo: !Ref pGlueTableStageMeucci2aCargo
        pSourceTableCargoTipo: !Ref pGlueTableStageMeucci2aCargotipo
        pSourceTableCuenta: !Ref pGlueTableStageMeucci2aCuenta
        pSourceTableEmpleado: !Ref pGlueTableStageMeucci2aEmpleado
        pSourceTableEmpleadoCuenta: !Ref pGlueTableStageMeucci2aEmpleadoCuenta
        pSourceTableEmpleadoModalidadTrabajo: !Ref pGlueTableStageMeucci2aEmpleadoModalidadTrabajo
        pSourceTableEmpleadoServicio: !Ref pGlueTableStageMeucci2aEmpleadoServicio
        pSourceTableEmpleadoSuperiores: !Ref pGlueTableStageMeucci2aEmpleadoSuperiores
        pSourceTableEmpleadoUbicacion: !Ref pGlueTableStageMeucci2aEmpleadoUbicacion
        pSourceTableModalidadTrabajo: !Ref pGlueTableStageMeucci2aModalidadTrabajo
        pSourceTableServicios: !Ref pGlueTableStageMeucci2aServicios
        pSourceTableSite: !Ref pGlueTableStageMeucci2aSite
        pSourceTableSociedad: !Ref pGlueTableStageMeucci2aSociedad
        pSourceTableSubarea: !Ref pGlueTableStageMeucci2aSubarea
        # Maestro-Equipos-Usuarios
        pGlueJobAnalyticsMaestroMaestroEquiposUsuarios: !Ref pGlueJobAnalyticsMaestroMaestroEquiposUsuarios
        pGlueJobAnalyticsScriptLocationMaestroMaestroEquiposUsuarios: !Ref pGlueJobAnalyticsScriptLocationMaestroMaestroEquiposUsuarios
        pGlueTableAnalyticsMaestroMaestroEquiposUsuarios: !Ref pGlueTableAnalyticsMaestroMaestroEquiposUsuarios
        pSourceTablempleadoCuentaLucent: !Ref pGlueTableStageMeucci2aEmpleadoCuentaLucent
        pSourceTableEmpleadoSistemaExterno: !Ref pGlueTableStageMeucci2aEmpleadoSistemaExterno
        pSourceTableSistemaExterno: !Ref pGlueTableStageMeucci2aSistemaExterno
      TimeoutInMinutes: 5
    
  rGlueCrawlerAnalyticsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateURLCrawlersAnalytics
      Parameters:
        pTagEnv: !Ref pTagEnv
        pTagProyect: !Ref pTagProyect
        pGlueCrawlerAnalyticsMaestro: !Ref pGlueCrawlerAnalyticsMaestro
        pGlueDatabaseAnalytics: !Ref pGlueDatabaseAnalytics
        pGlueCrawlerAnalyticsMaestroPathRoot: !Ref pGlueCrawlerAnalyticsMaestroPathRoot
        pProcessingGlueExecutionRoleStack: !Ref pArnGlueExecutionRoleStack
      TimeoutInMinutes: 5

  rGlueWorkflowStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateURLWorkflows
      Parameters:
        pTagEnv: !Ref pTagEnv
        pTagProyect: !Ref pTagProyect
        pGlueWorkflowMaestro: !Ref pGlueWorkflowMaestro
      TimeoutInMinutes: 5

  rGlueTriggerAnalyticsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateURLTriggerAnalytics
      Parameters:
        pGlueCrawlerTriggerAnalyticsMaestro: !Ref pGlueCrawlerTriggerAnalyticsMaestro
        pGlueWorkflowMaestro: !GetAtt rGlueWorkflowStack.Outputs.rGlueWorkflowMaestroName
        pGlueCrawlerAnalyticsMaestro: !GetAtt rGlueCrawlerAnalyticsStack.Outputs.rGlueCrawlerAnalyticsMaestroName
        pGlueJobAnalyticsMaestroMaestroEquipos: !GetAtt rGlueJobsAnalyticsStack.Outputs.rGlueJobAnalyticsMaestroMaestroEquiposName
        pGlueJobAnalyticsMaestroMaestroEquiposUsuarios: !GetAtt rGlueJobsAnalyticsStack.Outputs.rGlueJobAnalyticsMaestroMaestroEquiposUsuariosName
        pGlueJobTriggerAnalyticsMaestro: !Ref pGlueJobTriggerAnalyticsMaestro
      TimeoutInMinutes: 5